const { chromium } = require('@playwright/test');
(async () => {
 const browser = await chromium.launch();
 const page = await browser.newPage({viewport:{width:Number(process.env.WIZARD_WIDTH || 390),height:844}});
 await page.goto('http://127.0.0.1:8000/login.php?next=crear_partido.php');
 await page.getByRole('button',{name:'Administrador',exact:true}).click();
 await page.locator('#adminPassword').fill(process.env.GOODFELLAS_ADMIN_PASSWORD || 'Goodfellas2026');
 await page.getByRole('button',{name:'Entrar como admin',exact:true}).click();
 await page.waitForURL('**/crear_partido.php');
 await page.waitForSelector('#participantSearchReact',{state:'attached'});
 const errors=[];
 page.on('pageerror', error=>errors.push(error.message));
 const form=page.locator('[data-match-wizard]');
 if(await form.locator('[data-match-players]').isVisible()) throw Error('Players shown before configuration');
 await form.locator('[name="num_teams"]').fill('5');
 await form.locator('[data-match-next]').click();
 if(await form.locator('[data-match-players]').isVisible()) throw Error('Invalid configuration accepted');
 await form.locator('[name="num_teams"]').fill('2');
 await form.locator('[data-match-next]').click();
 await page.locator('#participantSearchReact').waitFor({state:'visible'});
 await page.locator('#participantSearchReact').fill('zzzzzzzz');
 await page.waitForTimeout(100);
 if(await page.locator('[data-player-row]:visible').count()) throw Error('Empty search');
 await page.locator('#participantSearchReact').fill('');
 const row=page.locator('[data-player-row]').first();
 const name=await row.locator('strong').innerText();
 await page.locator('#participantSearchReact').fill(name);
 await row.locator('[data-participant-toggle]').click();
 await page.waitForTimeout(150);
 await page.getByRole('button',{name:'Convocados',exact:true}).click();
 await page.waitForTimeout(150);
 if(await page.locator('[data-player-row]:visible').count()!==1) throw Error('Selected filter: '+await page.locator('[data-player-row]:visible').count()+' checked '+await page.locator('input[name="participants[]"]:checked').count());
 await form.locator('[data-match-back]').click();
 await form.locator('[name="num_teams"]').fill('3');
 await form.locator('[data-match-next]').click();
 const expected=3*Number(await form.locator('[name="players_per_team"]').inputValue());
 const counts=await page.locator('[data-match-cup-total]').allTextContents();
 if(counts.some(value=>Number(value)!==expected)) throw Error('Stale header counts');
 if(errors.length) throw Error(errors.join(', '));
 if(!await row.locator('input').isChecked()) throw Error('Selection lost');
 await page.screenshot({path:`outputs/crear-fecha-pasos-${process.env.WIZARD_WIDTH || 390}.png`,fullPage:true});
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
 if(overflow) throw Error('Mobile overflow');
 console.log('PASS: mobile steps, search, selected filter, preserved selection, no overflow');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
