const { test, expect } = require('@playwright/test');
const BASE_URL = process.env.BASE_URL || 'http://127.0.0.1:8000';
test.use({ hasTouch: true });

test('desktop drag and mobile destination list exchange players without saving', async ({ page }) => {
  test.setTimeout(90000);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto(`${BASE_URL}/login.php?next=sorteo_legacy_csv.php%3Fmatch_id%3D188`);
  await page.locator('#login-admin').evaluate(node => { node.open = true; });
  await page.locator('#adminPassword').fill(process.env.GOODFELLAS_ADMIN_PASSWORD || 'Goodfellas2026');
  await page.getByRole('button', { name: /Entrar como admin|Ingresar/i }).click();
  await page.locator('#generateTeamsButton').click();
  const cards = team => page.locator(`[data-sorteo-drag-player][data-team-index="${team}"]:not([data-assigned-position="ARQ"])`);
  await expect(cards(0).first()).toBeVisible({ timeout: 60000 });
  const source = cards(0).first();
  const target = cards(1).first();
  const sourceKey = await source.getAttribute('data-player-key');
  const targetKey = await target.getAttribute('data-player-key');
  const sourcePosition = await source.getAttribute('data-assigned-position');
  const targetPosition = await target.getAttribute('data-assigned-position');
  await source.scrollIntoViewIfNeeded();
  await target.scrollIntoViewIfNeeded();
  const a = await source.boundingBox();
  const b = await target.boundingBox();
  await page.mouse.move(a.x + a.width / 2, a.y + a.height / 2);
  await page.mouse.down();
  await page.mouse.move(b.x + b.width / 2, b.y + b.height / 2, { steps: 20 });
  await page.mouse.up();
  await expect(page.locator(`[data-sorteo-drag-player][data-player-key="${sourceKey}"]`)).toHaveAttribute('data-team-index', '1');
  await expect(page.locator(`[data-sorteo-drag-player][data-player-key="${targetKey}"]`)).toHaveAttribute('data-team-index', '0');
  await expect(page.locator('[data-undo-player-exchange]')).toHaveCount(2);
  await page.locator(`[data-undo-player-exchange="${sourceKey}"]`).click();
  await expect(page.locator(`[data-sorteo-drag-player][data-player-key="${sourceKey}"]`)).toHaveAttribute('data-team-index', '0');
  await expect(page.locator(`[data-sorteo-drag-player][data-player-key="${sourceKey}"]`)).toHaveAttribute('data-assigned-position', sourcePosition);
  await expect(page.locator(`[data-sorteo-drag-player][data-player-key="${targetKey}"]`)).toHaveAttribute('data-assigned-position', targetPosition);
  await expect(page.locator('[data-undo-player-exchange]')).toHaveCount(0);
  await page.setViewportSize({ width: 390, height: 844 });
  const mobileSource = cards(0).first();
  const mobileKey = await mobileSource.getAttribute('data-player-key');
  const mobilePosition = await mobileSource.getAttribute('data-assigned-position');
  const beforeCounts = [await cards(0).count(), await cards(1).count()];
  await mobileSource.tap();
  const panel = page.getByRole('region', { name: 'Mover o intercambiar jugador' });
  await expect(panel).toBeVisible();
  await page.screenshot({ path: 'test-results/sorteo-mobile-exchange.png' });
  await panel.locator('fieldset button:enabled').first().click();
  await expect(panel).toHaveCount(0);
  await expect(page.locator(`[data-sorteo-drag-player][data-player-key="${mobileKey}"]`)).toHaveAttribute('data-team-index', '1');
  expect([await cards(0).count(), await cards(1).count()]).toEqual(beforeCounts);
  await expect(page.locator('[data-undo-player-exchange]')).toHaveCount(2);
  await page.locator(`[data-undo-player-exchange="${mobileKey}"]`).scrollIntoViewIfNeeded();
  await expect(page.getByText('No se encontro el jugador que estas moviendo.', { exact: true })).toHaveCount(0);
  await page.screenshot({ path: 'test-results/sorteo-exchange-indicator.png' });
  await page.locator(`[data-undo-player-exchange="${mobileKey}"]`).tap();
  await expect(page.locator(`[data-sorteo-drag-player][data-player-key="${mobileKey}"]`)).toHaveAttribute('data-team-index', '0');
  await expect(page.locator(`[data-sorteo-drag-player][data-player-key="${mobileKey}"]`)).toHaveAttribute('data-assigned-position', mobilePosition);
  await expect(page.locator('[data-undo-player-exchange]')).toHaveCount(0);
  await expect(panel).toHaveCount(0);
});

test('mobile courts scroll horizontally and edge dragging reaches the other team', async ({ page }) => {
  test.setTimeout(90000);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${BASE_URL}/login.php?next=sorteo_legacy_csv.php%3Fmatch_id%3D188`);
  await page.locator('#login-admin').evaluate(node => { node.open = true; });
  await page.locator('#adminPassword').fill(process.env.GOODFELLAS_ADMIN_PASSWORD || 'Goodfellas2026');
  await page.getByRole('button', { name: /Entrar como admin|Ingresar/i }).click();
  await page.locator('#generateTeamsButton').click();
  const scroller = page.locator('[data-teams-scroller]');
  await expect(scroller).toBeVisible({ timeout: 60000 });
  const geometry = await scroller.evaluate(node => ({ width: node.clientWidth, total: node.scrollWidth, tops: [...node.children].map(child => child.getBoundingClientRect().top), pageWidth: document.documentElement.scrollWidth }));
  expect(geometry.total).toBeGreaterThan(geometry.width * 1.9);
  expect(geometry.tops[0]).toBe(geometry.tops[1]);
  expect(geometry.pageWidth).toBeLessThanOrEqual(390);
  const navigation = page.getByRole('group', { name: 'Elegir cancha' });
  await navigation.getByRole('button').nth(1).click();
  await expect.poll(() => scroller.evaluate(node => node.scrollLeft)).toBeGreaterThan(geometry.width * .9);
  await navigation.getByRole('button').first().click();
  await expect.poll(() => scroller.evaluate(node => node.scrollLeft)).toBeLessThan(2);
  const source = page.locator('[data-sorteo-drag-player][data-team-index="0"]:not([data-assigned-position="ARQ"])').first();
  const target = page.locator('[data-sorteo-drag-player][data-team-index="1"]:not([data-assigned-position="ARQ"])').first();
  const sourceKey = await source.getAttribute('data-player-key');
  const targetKey = await target.getAttribute('data-player-key');
  await source.evaluate(node => node.scrollIntoView({ block: 'center', inline: 'nearest' }));
  const a = await source.boundingBox();
  const bounds = await scroller.boundingBox();
  const cdp = await page.context().newCDPSession(page);
  const point = (x, y) => [{ x, y, id: 1 }];
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: point(a.x + a.width / 2, a.y + a.height / 2) });
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: point(bounds.x + bounds.width - 4, a.y + a.height / 2) });
  await expect.poll(() => scroller.evaluate(node => node.scrollLeft)).toBeGreaterThan(geometry.width * .98);
  const b = await target.boundingBox();
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: point(b.x + b.width / 2, b.y + b.height / 2) });
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
  await expect(page.locator(`[data-sorteo-drag-player][data-player-key="${sourceKey}"]`)).toHaveAttribute('data-team-index', '1');
  await expect(page.locator(`[data-sorteo-drag-player][data-player-key="${targetKey}"]`)).toHaveAttribute('data-team-index', '0');
  await expect(scroller).toHaveAttribute('data-dragging', 'false');
  await page.screenshot({ path: 'test-results/sorteo-horizontal-mobile.png' });
  const downloadReady = page.waitForEvent('download');
  await page.getByRole('button', { name: 'JPG', exact: true }).click();
  const download = await downloadReady;
  const exportPath = 'test-results/sorteo-horizontal-export.jpg';
  await download.saveAs(exportPath);
  const base64 = require('node:fs').readFileSync(exportPath).toString('base64');
  const dimensions = await page.evaluate(async data => {
    const image = new Image();
    image.src = `data:image/jpeg;base64,${data}`;
    await image.decode();
    return { width: image.naturalWidth, height: image.naturalHeight };
  }, base64);
  // La captura apila los equipos (una cancha debajo de la otra), asi que el ancho es el
  // de una cancha y el alto cubre las dos tarjetas.
  expect(dimensions.width).toBeLessThanOrEqual(geometry.width * 2);
  expect(dimensions.height).toBeGreaterThan(dimensions.width);
});
