const { spawn } = require('node:child_process');
const fs = require('node:fs/promises');
const path = require('node:path');
const chromePath = 'C:/Program Files/Google/Chrome/Application/chrome.exe';
const userDataDir = path.resolve('.tmp/chrome-mobile-shots');
const outDir = path.resolve('.tmp/mobile-shots');
const port = 9224;
const pages = ['index.php','jugadores.php','encuentros.php','capitanes.php','finalizar_partido.php','estadisticas.php','sorteo_legacy_csv.php?match_id=29'];
async function sleep(ms){return new Promise(r=>setTimeout(r,ms));}
async function getJson(url){return (await fetch(url)).json();}
class CDP{constructor(wsUrl){this.ws=new WebSocket(wsUrl);this.id=0;this.pending=new Map();this.ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id&&this.pending.has(m.id)){const p=this.pending.get(m.id);this.pending.delete(m.id);m.error?p.reject(new Error(JSON.stringify(m.error))):p.resolve(m.result)}}}async open(){await new Promise((resolve,reject)=>{this.ws.onopen=resolve;this.ws.onerror=reject})}send(method,params={}){const id=++this.id;this.ws.send(JSON.stringify({id,method,params}));return new Promise((resolve,reject)=>this.pending.set(id,{resolve,reject}))}close(){this.ws.close()}}
(async()=>{await fs.rm(userDataDir,{recursive:true,force:true});await fs.rm(outDir,{recursive:true,force:true});await fs.mkdir(outDir,{recursive:true});const chrome=spawn(chromePath,[`--remote-debugging-port=${port}`,`--user-data-dir=${userDataDir}`,'--headless=new','--disable-gpu','--no-first-run','--no-default-browser-check','about:blank'],{stdio:'ignore'});try{for(let i=0;i<40;i++){try{await getJson(`http://127.0.0.1:${port}/json/version`);break}catch{await sleep(250)}}const tabs=await getJson(`http://127.0.0.1:${port}/json`);const cdp=new CDP((tabs.find(t=>t.type==='page')||tabs[0]).webSocketDebuggerUrl);await cdp.open();await cdp.send('Page.enable');await cdp.send('Runtime.enable');await cdp.send('Network.enable');await cdp.send('Emulation.setDeviceMetricsOverride',{width:360,height:900,deviceScaleFactor:3,mobile:true});await cdp.send('Page.navigate',{url:'http://127.0.0.1:8000/login.php'});await sleep(500);await cdp.send('Runtime.evaluate',{awaitPromise:true,expression:`fetch('/login.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'password=Goodfellas2026&next=index.php',credentials:'include'}).then(r=>r.text())`});for(const page of pages){await cdp.send('Page.navigate',{url:`http://127.0.0.1:8000/${page}`});await sleep(900);const data=await cdp.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});await fs.writeFile(path.join(outDir, page.replace(/[?=&]/g,'_')+'.png'), Buffer.from(data.data,'base64'));}cdp.close();}finally{chrome.kill();}})().catch(e=>{console.error(e);process.exit(1)});
